### ISSUE TITLE
"Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect."  Balance of wallet is zero.

### ISSUE THREAD

**Issue by wrexc** [XCurrency/xc#5]
### Describe the issue
Opening wallet.dat file results in a warning:

"Warning: error reading wallet.dat!  All keys read correctly, but transaction data or address book entries might be missing or incorrect."

In fact, the wallet value appears as zero when the balance is in fact non-zero.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1.  Download and open the linux XC wallet ("xc3-qt") from ubuntu 14.04LTS.
2.  Close the wallet, and replace the auto-generated wallet.dat file with a non-zero-balance wallet file.
3.  Open the XC wallet again.
4.  At the warning message prompt during "loading wallet" stage, select "OK" to proceed to the wallet chain sync and gui load.
5.  When done sync'ing, examine the balance.  It will be zero.

### Expected behavior
Wallet should load the accurate balance.

### Actual behavior
Wallet loads with a zero balance.

### What version of XC are you using?
XC v3.0.02 pre-release commit id b609ec3fe23dc91754e329e25ab9fb6f76a4bc23

Downloaded from github directly via https://github.com/XCurrency/xc/releases/download/v3.0.02/xcurrency-3.0.02-x86_64-linux-gnu.tar.gz and unzipped/untarred using ubuntu built-in archive manager apps.

### Machine specs:
- OS:  ubuntu desktop x64 14.04 LTS running on virtual box Version 5.1.30 r118389 (Qt5.6.2)
- CPU:  AMD A10-6800k
- RAM:  2048MB
- Disk size:  Elastic VDI.
- Disk Type (HD/SDD):  Virtual running on a 2TB base HDD.

### Any extra information that might be useful in the debugging process.
First, this error may be due to the new wallet sync'ing on the new chain while the wallet.dat was created and loaded using the old chain.  Am not aware if this is the case, but if so, this may explain the zero balance when the wallet.dat is provably not corrupted.  Wallet.dat works on a windows 7 x64 machine without issue, and displays proper balance, using XCurrency version v0.9.4.1a.XCurrency-REV2.

Note that the wallet file(s) were created on a windows 7 x64 machine, originally, and then copied to the ubuntu build using a samba share.  This should not be significant, though line endings could possibly be at play given the unusual nature of the use case.  This workflow was chosen because there is not yet a windows release of the wallet.

Also, no error is produced when the wallet is unlocked using the passphrase, though this has no bearing on the wallet balance - it still stays at zero.  Likewise, the wallet can be relocked without error.

debug.log file available on request, or parts thereof if you can tell me what you need - it's a 2MB file.

![xc-wallet-with-error-2018-01-13_20-01-12 - copy](https://user-images.githubusercontent.com/35500380/35005124-b3d4bd12-faaf-11e7-99f2-26a01ad65b3f.png)

**Comment by atcsecure** [comment]
This is the expected behavior if your trying to use a wallet.dat from the old-chain/old-wallet.

Balances will also be zero on the new chain, until the swap takes place

**Comment by wrexc** [comment]
OK.  Assumed the new wallet would be on the old chain until the swap.  If it is expected behaviour, I'll just close it.
