### ISSUE TITLE
XCurrency core wallet halts at 75% on "synchronizing service node winners..."; "Signature rejected, too far into the future" showing up in logs.

### ISSUE THREAD

**Issue by wrexc** [XCurrency/xc#6]
## Describe the issue
During the "synchronizing additional data" phase, wallet progress bar freezes on "synchronizing service node winners..." substep.  In this case, at 75% of progress.

## Can you reliably reproduce the issue?
Yes, most of the time.  On one occasion of about four it worked, and the details of the one working are not available, but the elapsed time was not over fifteen minutes before it worked.

## If so, please list the steps to reproduce below:
1.  Open core wallet with or without a wallet.dat file (if none is found, one will be created).
2.  Wait for chain to sync.
3.  Observe the progress bar at the bottom of the UI.  It will freeze, probably at 75% as of this date and time, with three peers, per the peers tab of the info pane:  104.238.198.165, 35.168.243.7, and 88.99.169.175.
4.  Check log file for errors.

![xc-wallet-servicenode-winner-halting-2018-01-16_10-52-22 - copy](https://user-images.githubusercontent.com/35500380/35006231-54e3ee64-fab3-11e7-94fc-c9b90d465740.png)

## Actual behavior
Progress of chain sync halts on the service node winners sync substep.  Clocked at around half an hour prior to giving up and shutting UI down.  Assuming it should finish long before that, based on the block height and what not.

## Expected Behavior
Progress bar completes to 100% and then hides or the progress subwindow is perhaps removed from memory.

## What version of XC are you using?
XC v3.0.02 pre-release commit id b609ec3

Downloaded from github directly via https://github.com/XCurrency/xc/releases/download/v3.0.02/xcurrency-3.0.02-x86_64-linux-gnu.tar.gz and unzipped/untarred using ubuntu built-in archive manager apps.

## Machine specs:
OS: ubuntu desktop x64 14.04 LTS running on virtual box Version 5.1.30 r118389 (Qt5.6.2)
CPU: AMD A10-6800k
RAM: 2048MB
Disk size: Elastic VDI.
Disk Type (HD/SDD): Virtual running on a 2TB base HDD.

## Any extra information that might be useful in the debugging process.

Does not appear to be a blocking process or thread - no "freezing" of UI.  Most if not all of other wallet functions operate, such as menus (did not test everything, just a few functions).

Debug log has a number of the following types of entries, chaining from one servicenode IP to the next, marking each in turn as misbehaving:

dseep - Signature rejected, too far into the future fc2a980431964dc28a54ac3e831aa09d925ddc31de91f9390f329ce21c14b0ed
2018-01-14 06:26:36 Misbehaving: 88.99.169.175:14333 (0 -> 1)

**Comment by atcsecure** [comment]
Unfortunately I'm not able to replicate that issue, please verify your local lock is accurate.   I just spun up a node in AWS and was able to sync the chain and snodes fairly quickly without any issues. 

Generally that error means your local time-clock is out of sync

**Comment by atcsecure** [comment]
It may be more effective to troubleshoot via xc's slack

**Comment by wrexc** [comment]
Right.  The time was close, but the day was *behind* by 2.  Not displaying date by default - only time, so had to dropdown the date/time to see that it was off.  NTP svc was running, and grepping the syslog showed it was sync'ing as it should, but it wasn't.  That's a first.  Had to manually change the time, then switch back to using NTP and it appears to be keeping sync with the atomic clocks as it should.

Test 1 worked, and it sync'd properly.  Shutdown soon thereafter.

Test 2 is presently stuck at 50% "synchronizing servicenodes...".  I see you released the win wallet moments ago.   I'll wait until the new windows wallet masses come online, and leave this running for a few hours in case it's just network congestion.  In any case, it's failing at a different state now, apparently _prior_ to reaching the servicenode winner determination state.

**Comment by wrexc** [comment]
Test 2 lasted until I shut it down several hours later.
Test 3 and test 4 succeeded - the 50% stuck error did not occur.
Test 5 kicked off with the 50% stuck error, and lasted for at least an hour.  May need to close this issue and open a new issue.  Don't think these are related anymore.

**Comment by wrexc** [comment]
Calling this issue fixed.  Most likely was the sysclock issue.  If I see the 50pct stuck error again, I'll keep an eye on it, but it seems all OK.
