### ISSUE TITLE
Wallet stuck on synchronzing sporks, synchronizing additional data at 25% with low peer count

### ISSUE THREAD

**Issue by wrexc** [XCurrency/xc#9]
### Describe the issue
Maximum peer count was three while others on slack were reporting teens and higher.  Restarted the wallet and now maximum peers has been two.
Now wallet is stuck on sync'ing sporks.  Consistently at 25%.

#### If so, please list the steps to reproduce below:
1.  Restart wallet.
2.  Wallet advances to sync'ing sporks state, and sticks at 25%.

### Expected behavior
Wallet should advance beyond this state, in a reasonable amount of time.  Half an hour or more is not reasonable.

### Actual behavior
Wallet sticks at this sync'ing sporks state.

### Screenshots.
![xc-wallet-stuck-at-syncing-sporks-25pct-2018-01-18_10-39-09 - copy](https://user-images.githubusercontent.com/35500380/35112642-e1f96994-fc3b-11e7-9841-d014284e1b10.png)

### What version of XC Core are you using?
v3.0.04
commit id: 97a21bcbf289e181f8f1aeb95d20eb9490c0a0e3

v3.0.02 on ubuntu

### Machine specs:
- OS:  Tested on BOTH win7 x64 and ubuntu 14.04LTS.  Same behaviour.

### Any extra information that might be useful in the debugging process.
Turned off Windows firewall completely.  No change.

**Comment by wrexc** [comment]
tooltip in ubuntu showing "synchronizing sporks" and below it "up to date" in both win7 and ubuntu.    Is this message reflecting the spork sync, or is the "up to date" referencing the block height?

![xc-syncing-sporks-says-up-to-date-in-tooltip-2018-01-18_10-49-34 - copy](https://user-images.githubusercontent.com/35500380/35113089-85c1cbce-fc3d-11e7-8e9c-cf747abffd65.png)

**Comment by wrexc** [comment]
Per @atcsecure one of the servicenode peers needed a kick.  Seems to have solved the problem.  Good to know for future repeats.  I believe more peers will be spun up to help mitigate this.

**Comment by PXLFuSSeL** [comment]
hy can you tell me what you excactly did? we tried forking another coin and got the same issue

**Comment by wrexc** [comment]
Check the times of your systems.  If the system clocks are off, it will cause just such a problem.  In this case, my client machine was not properly sync'ing to NIST as it should, and it was off by hours.

kind regards

----- Original Message -----

**Comment by ArcanaCoin** [comment]
any solution?

**Comment by wrexc** [comment]
Your times are probably off.  Check your client computer clock to make
sure it is within a few minutes of actual time in your time zone.  Make
sure your other nodes clocks are accurate, too.

**Comment by bestsolutionit** [comment]
hello,  kindly tell me how can I check computer clock.   I can see the correct time and timezone on my computer.
